name: Build & Deploy Website
on:
  push:
    branches:
      - main
    paths-ignore:
    - 'scratch/**'
jobs:
    hosting:
      name: Build & Deploy
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1

        - uses: subosito/flutter-action@v1
          with:
            channel: 'dev'

        - name: Build Website
          run: |
            flutter config --enable-web
            flutter pub get
            flutter build web --release
          working-directory: ./

        - name: Deploy Firebase Hosting
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting:flutter-allin
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
            PROJECT_PATH: ./


